aliases:
  - &install_yarn_version
    name: Install specific Yarn version
    command: |
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
      echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV

  - &restore_yarn_cache
    name: Restore Yarn cache
    keys:
      - yarn-{{ .Branch }}-packages-{{ checksum "yarn.lock" }}

  - &save_yarn_cache
    name: Save Yarn cache
    key: yarn-{{ .Branch }}-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

  - &run_yarn_install
    name: Install dependencies
    command: yarn install

defaults: &defaults
  working_directory: ~/react-instantsearch
  docker:
    - image: circleci/node:8.15.1@sha256:bb3dffce8a53e0efc79b183144c64a31486f539a36e982d214e128a387f96176

version: 2
jobs:
  test_build:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Build & Test packages size
          command: yarn test:build

  test_unit:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Lint & Code styles
          command: yarn lint
      - run:
          name: Type checking
          command: yarn type-check
      - run:
          name: Unit Tests
          command: yarn test --maxWorkers=4

  test_e2e:
    <<: *defaults
    docker:
      - image: circleci/node:8.15.1-browsers@sha256:be8977fcbcc43ebf75ad1704a677fc9949df97d75f404ba560b93662f2d31c98
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: E2E Tests
          command: yarn test:e2e

  test_examples:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Build & Test examples
          command: yarn test:examples

workflows:
  version: 2
  ci:
    jobs:
      - test_build
      - test_unit
      - test_e2e
      - test_examples
